env:
  GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GRADLE_OPTS: -Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server
    -XX:+UseG1GC
  JAVA_OPTS: -Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC
  JDK_CURRENT: 17
  SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  TERM: xterm-256color
jobs:
  build:
    needs: cancel-previous-runs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      name: Build with Gradle
      run: mvn clean install
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
  cancel-previous-runs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    timeout-minutes: 1
  publish-snapshots:
    if: ${{ github.event_name == 'push' }}
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      if: ${{ env.SONATYPE_USER != null && env.SONATYPE_PWD != null }}
      name: Publish SNAPSHOTs
      run: mvn deploy --settings ./.github/workflows/settings.xml
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
